---
title: Change sound effects
hero_image: images/banner.png
description: Change sound effects
version: 4
listed: false
copyedit: false
last_tested: "2021-06-08"
steps:
  - 
    title: Change sound effects
