---
title: Newid effeithiau sain
hero_image: images/banner.png
description: Newid effeithiau sain
version: 4
listed: false
copyedit: false
last_tested: "2021-06-08"
steps:
  - 
    title: Newid effeithiau sain
