---
title: Alterar efeitos sonoros
hero_image: images/banner.png
description: Alterar efeitos sonoros
version: 4
listed: false
copyedit: false
last_tested: "2021-06-08"
steps:
  - title: Alterar efeitos sonoros
