---
title: Cambia los efectos de sonido
hero_image: images/banner.png
description: Cambia los efectos de sonido
version: 4
listed: false
copyedit: false
last_tested: "2021-06-08"
steps:
  - 
    title: Cambia los efectos de sonido
