---
title: Changer les effets sonores
hero_image: images/banner.png
description: Changer les effets sonores
version: 4
listed: false
copyedit: false
last_tested: "2021-06-08"
steps:
  - title: Changer les effets sonores
